# Title of the page
title: "Sof's life"
# Your name
author: Sofía Saulés
# Show a link to LinkedIn in the header intro. Comment out to disable.
# linkedin: https://www.linkedin.com/in/guptaneil/
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
  url: https://neil.gg
  title: neil.gg
# show today marker at end of timeline
show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - events:
    - Noviembre 1992: "Nací en la, no tan concurrida hasta el momento, CDMX, antes DF."
    - Marzo 1994: "Nació mi compañero de aventuras y de la vida, mi hermano."
    - Agosto 1999: "Entré a la primaria, un niño me preguntó en qué año había nacido, le dije que en 1998 y se burló de mí, no sabía nada de la vida. Fue la primera vez que sentí vergüenza."
  - name: 2000's
    events:
    
    - November 2009: >-
        📷 Neil gets a DSLR camera and picks up <a href="https://photos.neil.gg" target="_blank" rel="noopener"
        title="See some of my photos">photography as a hobby</a>.
  - name: 2010's
    events:
    - June 2010: "✈️ Neil studies abroad in Paris."
    - October 2010: 🎂 Neil turns 20.
    - October 2011: 🏆 Neil becomes a ThinkChicago Fellow.
    - December 2011: >-
        💻 Neil works with <a href="https://vimeo.com/33098706" target="_blank" rel="noopener" title="Watch a slideshow of
        my team's trip to Haiti">Haiti's Ministry of Education, OLPC, and IIT</a> to deploy solar panels, laptops, and servers pre-loaded with
        Wikipedia in a Haitian school.
    - May 2012: >-
        🎓 Neil graduates from Illinois Institute of Technology with degrees in Computer Science & Psychology, a minor in Entrepreneurship,
        and a specialization in Artificial Intelligence.
    - June 2012: 👨‍💻 Neil cofounds <a href="https://www.neil.gg/work/tabule" target="_blank">Tabule</a>, a smart student planner powered by AI.
    - July 2012: >-
        🎙 Neil does a <a href="https://vimeo.com/45029595" target="_blank" rel="noopener">press conference with Rahm Emanuel</a> about Tabule and
        Chicago tech. Emanuel says "Chicago needs more Neils." Neil agrees for exactly 3 years.
    - June 2013: 👨‍💻 Tabule is acqui-hired by Eligo, where Neil builds tools to automate repetitive processes.
    - August 2014: >-
        👨‍💻 Neil builds the <a href="https://www.youtube.com/watch?v=oo6b5gZqm0A" target="_blank" rel="noopener" title="Watch the
        Flocks in action">Flocks</a>, an IoT art installation that reacts to its environment and Twitter. Cisco displays two at their Internet of Things
        conference.
    - December 2014: >-
        👨‍💻 Neil works with Eren Bali to prototype Maven, the operating system for your business.
    - May 2015: 👨‍💻 Neil joins Instructure to build educational software again.
    - July 2015: 🤕 Neil gets hit by a bicyclist named Neil G. He wakes up in the hospital with 14 stitches on his face but no new superpowers.
    - November 2015: 🏠 Neil buys his first home in South Loop.
    - January 2018: 🧠 Neil builds an AI to manage his home for him.
    - September 2018: 🛠 Neil turns his second bedroom into a prototyping lab with four 3D printers and a soldering bench.
    - January 2019: 🏆 Neil receives a grant from Y Combinator to keep building his smart home tech.
    - April 2019: >-
        👨‍💻 Neil founds <a href="https://hiome.com" target="_blank" rel="noopener">Hiome</a> to change how we use our homes.
  - name: 2020's
    events:
    - May 2020: >-
        🦠 Neil launches <a href="https://researchexplained.neil.gg" target="_blank" rel="noopener">Research Explained</a> to make visual
        summaries of COVID-19 research accessible to anyone.
    - August 2020: 👨‍💻 Neil joins Guilded to build the community platform for gamers.
    - October 2020: 🎂 Neil turns 30 in the midst of a global pandemic.
    - April 2021: 🏠 Neil moves to a new home in Streeterville.
    - May 2021: 🐶 Neil's sister adopts <a href="https://photos.neil.gg/wally" target="_blank" title="Meet our beautiful greyhound!">Wally</a>, fulfilling a life-long Gupta sibling dream and granting him unlimited dog time with none of the work.
    - August 2021: 👾 Guilded is acquired by Roblox, and Neil quickly learns who in his life has kids.
