# Title of the page
title: "Chars's life"
# Your name
author: Carlos Rueda
# Show a link to LinkedIn in the header intro. Comment out to disable.
# linkedin: 
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
  url: https://neil.gg
  title: neil.gg
# show today marker at end of timeline
show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - name: 1990's
   - events:
    - Julio 1989: "Naci."
    - Abril 1998: "Ingrese a un hospital para vivir ahi poco mas de 12 meses" 
    - Julio 1999: "Sali del hospital en silla de ruedas y mama parte"
  - name: 2000's
   - events:
    - Diciembre 2000: "Comence a dar mis primeros pasos en forma y hacia una vida normal."
    - Febrero 2001: "Conoci el basketball para enamorarme de la vida."
    - Marzo 2007: "Una segunda recaida y resurgia la duda sobre la naturaleza de mi cuerpo"
    - Diciembre 2008: "Una segunda oportunidad"
    - Agosto 2013: "Mama regreso"
  - name: 2010's
    events:
    - Agosto 2019: "Tercera recaida. La familia se unio despues de una gran ausencia."
    - Diciembre 2019: "El misterio se resolvio. Se llama STILL" 
  - name: 2020's
    events:
    - Noviembre 2020: "Fingir en el cv para poder chambear y recuperar el animo."
    - Agosto 2021: "Conoceria a la persona que me desbloqueo varios esenarios en esta vida"
    - Marzo 2023: "Se cae el servidor y es momento de salir de la banca"
    - Julio 2023: "Inivitarla a salir y ver slamdunk con ella"
