# Title of the page
title: "Sof's life"
# Your name
author: Sofía Saulés
# Show a link to LinkedIn in the header intro. Comment out to disable.
# linkedin: 
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
  url: https://neil.gg
  title: neil.gg
# show today marker at end of timeline
show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - events:
    - Noviembre 1992: "Nací en la, no tan concurrida hasta el momento, CDMX, antes DF."
    - Marzo 1994: "Nació mi compañerito de aventuras y de la vida, mi hermano."
    - Agosto 1999: "Entré a la primaria, un niño me preguntó en qué año había nacido, le dije que en 1998 y se burló de mí. Fue la primera vez que sentí vergüenza, no sabía nada de la vida ni de fechas."
  - name: 2000's
   - events:
    - Diciembre 2005: "Falleció el hermano de mi mamá, tenía 30 años. Comprendí lo finita que era la vida."
    - Agosto 2008: "Entré a la preparatoria, mi primer logro. Mi prima no se quedó entonces en la familia optaron por no felicitarme o hacerlo en "secreto"."
  - name: 2010's
    events:
    - Agosto 2011: "Entré a la Universidad a estudiar Biología, aunque yo quería estudiar Letras. Estaba indecisa."
    - Diciembre 2012: "Tuve mi primera relación significativa, creí que ahí iba a estar por siempre, pero sólo fueron cuatro años y medio." 
    - Noviembre 2017: "Me titulé. Ya quería cerrar ese ciclo"
    
  - name: 2020's
    events:
    - Abril 2023: "Entré a estudiar a Laboratoria. Benditas segundas oportunidades"
